on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Set addon version
        run: sed --in-place '/<addon/ s/version="[^"]*"/version="'${GITHUB_REF##*/v}'"/' repository.stash/addon.xml
      - name: Create addon zip
        run: |
          mkdir -p /tmp/repository.stash
          rsync -a repository.stash/addon.xml /tmp/repository.stash
          cd /tmp/
          zip -r repository.stash.zip repository.stash/
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: repository.stash.zip
          path: /tmp/repository.stash.zip

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: repository.stash.zip
      - uses: marvinpinto/action-automatic-releases@v1.1.1
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          prerelease: false
          files: |
            repository.stash.zip

